/**
 * Stock Symbols Database
 * Contains all S&P 500 stocks + popular ETFs for autocomplete functionality
 */

export interface StockInfo {
  symbol: string
  name: string
  sector?: string
}

// Full S&P 500 + Popular ETFs (500+ stocks)
export const POPULAR_STOCKS: StockInfo[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // INFORMATION TECHNOLOGY (70+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Technology' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Technology' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Technology' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'Technology' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Technology' },
  { symbol: 'IBM', name: 'International Business Machines', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Technology' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Technology' },
  { symbol: 'MU', name: 'Micron Technology Inc.', sector: 'Technology' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Technology' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', sector: 'Technology' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', sector: 'Technology' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', sector: 'Technology' },
  { symbol: 'MSI', name: 'Motorola Solutions Inc.', sector: 'Technology' },
  { symbol: 'APH', name: 'Amphenol Corporation', sector: 'Technology' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Technology' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', sector: 'Technology' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.', sector: 'Technology' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.', sector: 'Technology' },
  { symbol: 'CTSH', name: 'Cognizant Technology', sector: 'Technology' },
  { symbol: 'IT', name: 'Gartner Inc.', sector: 'Technology' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems', sector: 'Technology' },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc.', sector: 'Technology' },
  { symbol: 'ANSS', name: 'ANSYS Inc.', sector: 'Technology' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Technology' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Technology' },
  { symbol: 'GLW', name: 'Corning Incorporated', sector: 'Technology' },
  { symbol: 'FSLR', name: 'First Solar Inc.', sector: 'Technology' },
  { symbol: 'CDW', name: 'CDW Corporation', sector: 'Technology' },
  { symbol: 'TYL', name: 'Tyler Technologies Inc.', sector: 'Technology' },
  { symbol: 'VRSN', name: 'VeriSign Inc.', sector: 'Technology' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corp.', sector: 'Technology' },
  { symbol: 'TER', name: 'Teradyne Inc.', sector: 'Technology' },
  { symbol: 'STX', name: 'Seagate Technology Holdings', sector: 'Technology' },
  { symbol: 'WDC', name: 'Western Digital Corp.', sector: 'Technology' },
  { symbol: 'NTAP', name: 'NetApp Inc.', sector: 'Technology' },
  { symbol: 'PTC', name: 'PTC Inc.', sector: 'Technology' },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc.', sector: 'Technology' },
  { symbol: 'QRVO', name: 'Qorvo Inc.', sector: 'Technology' },
  { symbol: 'GEN', name: 'Gen Digital Inc.', sector: 'Technology' },
  { symbol: 'JNPR', name: 'Juniper Networks Inc.', sector: 'Technology' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc.', sector: 'Technology' },
  { symbol: 'FFIV', name: 'F5 Inc.', sector: 'Technology' },
  { symbol: 'EPAM', name: 'EPAM Systems Inc.', sector: 'Technology' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.', sector: 'Technology' },
  { symbol: 'SEDG', name: 'SolarEdge Technologies', sector: 'Technology' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', sector: 'Technology' },
  { symbol: 'ARM', name: 'Arm Holdings plc', sector: 'Technology' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.', sector: 'Technology' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', sector: 'Technology' },
  { symbol: 'ASML', name: 'ASML Holding N.V.', sector: 'Technology' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor', sector: 'Technology' },
  { symbol: 'BB', name: 'BlackBerry Limited', sector: 'Technology' },

  // ═══════════════════════════════════════════════════════════════════════════
  // FINANCIALS (65+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'BRK.A', name: 'Berkshire Hathaway Inc. (Class A)', sector: 'Financial' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc. (Class B)', sector: 'Financial' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financial' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financial' },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Financial' },
  { symbol: 'BAC', name: 'Bank of America Corp.', sector: 'Financial' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Financial' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.', sector: 'Financial' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Financial' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Financial' },
  { symbol: 'AXP', name: 'American Express Company', sector: 'Financial' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financial' },
  { symbol: 'SCHW', name: 'Charles Schwab Corporation', sector: 'Financial' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Financial' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies', sector: 'Financial' },
  { symbol: 'PGR', name: 'Progressive Corporation', sector: 'Financial' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'Financial' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Financial' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financial' },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financial' },
  { symbol: 'PNC', name: 'PNC Financial Services', sector: 'Financial' },
  { symbol: 'MCO', name: 'Moody\'s Corporation', sector: 'Financial' },
  { symbol: 'TFC', name: 'Truist Financial Corp.', sector: 'Financial' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', sector: 'Financial' },
  { symbol: 'AFL', name: 'Aflac Incorporated', sector: 'Financial' },
  { symbol: 'MET', name: 'MetLife Inc.', sector: 'Financial' },
  { symbol: 'AIG', name: 'American International Group', sector: 'Financial' },
  { symbol: 'PRU', name: 'Prudential Financial Inc.', sector: 'Financial' },
  { symbol: 'TRV', name: 'The Travelers Companies', sector: 'Financial' },
  { symbol: 'MSCI', name: 'MSCI Inc.', sector: 'Financial' },
  { symbol: 'ALL', name: 'Allstate Corporation', sector: 'Financial' },
  { symbol: 'AMP', name: 'Ameriprise Financial Inc.', sector: 'Financial' },
  { symbol: 'COF', name: 'Capital One Financial Corp.', sector: 'Financial' },
  { symbol: 'DFS', name: 'Discover Financial Services', sector: 'Financial' },
  { symbol: 'BK', name: 'Bank of New York Mellon Corp.', sector: 'Financial' },
  { symbol: 'STT', name: 'State Street Corporation', sector: 'Financial' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Financial' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', sector: 'Financial' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Inc.', sector: 'Financial' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Financial' },
  { symbol: 'RF', name: 'Regions Financial Corp.', sector: 'Financial' },
  { symbol: 'CFG', name: 'Citizens Financial Group Inc.', sector: 'Financial' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation', sector: 'Financial' },
  { symbol: 'FRC', name: 'First Republic Bank', sector: 'Financial' },
  { symbol: 'SIVB', name: 'SVB Financial Group', sector: 'Financial' },
  { symbol: 'CINF', name: 'Cincinnati Financial Corp.', sector: 'Financial' },
  { symbol: 'WRB', name: 'W. R. Berkley Corporation', sector: 'Financial' },
  { symbol: 'TROW', name: 'T. Rowe Price Group Inc.', sector: 'Financial' },
  { symbol: 'BRO', name: 'Brown & Brown Inc.', sector: 'Financial' },
  { symbol: 'RJF', name: 'Raymond James Financial Inc.', sector: 'Financial' },
  { symbol: 'L', name: 'Loews Corporation', sector: 'Financial' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc.', sector: 'Financial' },
  { symbol: 'CBOE', name: 'Cboe Global Markets Inc.', sector: 'Financial' },
  { symbol: 'FDS', name: 'FactSet Research Systems', sector: 'Financial' },
  { symbol: 'MKTX', name: 'MarketAxess Holdings Inc.', sector: 'Financial' },
  { symbol: 'IVZ', name: 'Invesco Ltd.', sector: 'Financial' },
  { symbol: 'BEN', name: 'Franklin Resources Inc.', sector: 'Financial' },
  { symbol: 'GL', name: 'Globe Life Inc.', sector: 'Financial' },
  { symbol: 'RE', name: 'Everest Re Group Ltd.', sector: 'Financial' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', sector: 'Financial' },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Financial' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.', sector: 'Financial' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.', sector: 'Financial' },

  // ═══════════════════════════════════════════════════════════════════════════
  // HEALTHCARE (65+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', sector: 'Healthcare' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Healthcare' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
  { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare' },
  { symbol: 'ELV', name: 'Elevance Health Inc.', sector: 'Healthcare' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'Healthcare' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', sector: 'Healthcare' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Healthcare' },
  { symbol: 'BSX', name: 'Boston Scientific Corp.', sector: 'Healthcare' },
  { symbol: 'CI', name: 'The Cigna Group', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health Corporation', sector: 'Healthcare' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', sector: 'Healthcare' },
  { symbol: 'BDX', name: 'Becton Dickinson and Company', sector: 'Healthcare' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.', sector: 'Healthcare' },
  { symbol: 'MCK', name: 'McKesson Corporation', sector: 'Healthcare' },
  { symbol: 'HUM', name: 'Humana Inc.', sector: 'Healthcare' },
  { symbol: 'BIIB', name: 'Biogen Inc.', sector: 'Healthcare' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corp.', sector: 'Healthcare' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc.', sector: 'Healthcare' },
  { symbol: 'A', name: 'Agilent Technologies Inc.', sector: 'Healthcare' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.', sector: 'Healthcare' },
  { symbol: 'RMD', name: 'ResMed Inc.', sector: 'Healthcare' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies', sector: 'Healthcare' },
  { symbol: 'MTD', name: 'Mettler-Toledo International', sector: 'Healthcare' },
  { symbol: 'CAH', name: 'Cardinal Health Inc.', sector: 'Healthcare' },
  { symbol: 'DXCM', name: 'DexCom Inc.', sector: 'Healthcare' },
  { symbol: 'COR', name: 'Cencora Inc.', sector: 'Healthcare' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings', sector: 'Healthcare' },
  { symbol: 'ILMN', name: 'Illumina Inc.', sector: 'Healthcare' },
  { symbol: 'WAT', name: 'Waters Corporation', sector: 'Healthcare' },
  { symbol: 'BAX', name: 'Baxter International Inc.', sector: 'Healthcare' },
  { symbol: 'HOLX', name: 'Hologic Inc.', sector: 'Healthcare' },
  { symbol: 'ALGN', name: 'Align Technology Inc.', sector: 'Healthcare' },
  { symbol: 'CNC', name: 'Centene Corporation', sector: 'Healthcare' },
  { symbol: 'MOH', name: 'Molina Healthcare Inc.', sector: 'Healthcare' },
  { symbol: 'LH', name: 'Labcorp Holdings Inc.', sector: 'Healthcare' },
  { symbol: 'DGX', name: 'Quest Diagnostics Inc.', sector: 'Healthcare' },
  { symbol: 'VTRS', name: 'Viatris Inc.', sector: 'Healthcare' },
  { symbol: 'TECH', name: 'Bio-Techne Corporation', sector: 'Healthcare' },
  { symbol: 'INCY', name: 'Incyte Corporation', sector: 'Healthcare' },
  { symbol: 'PODD', name: 'Insulet Corporation', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'Moderna Inc.', sector: 'Healthcare' },
  { symbol: 'CTLT', name: 'Catalent Inc.', sector: 'Healthcare' },
  { symbol: 'WST', name: 'West Pharmaceutical Services', sector: 'Healthcare' },
  { symbol: 'STE', name: 'STERIS plc', sector: 'Healthcare' },
  { symbol: 'TFX', name: 'Teleflex Incorporated', sector: 'Healthcare' },
  { symbol: 'XRAY', name: 'DENTSPLY SIRONA Inc.', sector: 'Healthcare' },
  { symbol: 'HSIC', name: 'Henry Schein Inc.', sector: 'Healthcare' },
  { symbol: 'PKI', name: 'Revvity Inc.', sector: 'Healthcare' },
  { symbol: 'BIO', name: 'Bio-Rad Laboratories Inc.', sector: 'Healthcare' },
  { symbol: 'RVTY', name: 'Revvity Inc.', sector: 'Healthcare' },
  { symbol: 'DVA', name: 'DaVita Inc.', sector: 'Healthcare' },
  { symbol: 'OGN', name: 'Organon & Co.', sector: 'Healthcare' },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONSUMER DISCRETIONARY (60+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'HD', name: 'Home Depot Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'NKE', name: 'Nike Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'LOW', name: 'Lowe\'s Companies Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'TJX', name: 'TJX Companies Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer Discretionary' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'AZO', name: 'AutoZone Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'MAR', name: 'Marriott International Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings', sector: 'Consumer Discretionary' },
  { symbol: 'GM', name: 'General Motors Company', sector: 'Consumer Discretionary' },
  { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumer Discretionary' },
  { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'YUM', name: 'Yum! Brands Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'LEN', name: 'Lennar Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'EBAY', name: 'eBay Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises', sector: 'Consumer Discretionary' },
  { symbol: 'DPZ', name: 'Domino\'s Pizza Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'ULTA', name: 'Ulta Beauty Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NVR', name: 'NVR Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'PHM', name: 'PulteGroup Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'EXPE', name: 'Expedia Group Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp.', sector: 'Consumer Discretionary' },
  { symbol: 'APTV', name: 'Aptiv PLC', sector: 'Consumer Discretionary' },
  { symbol: 'GRMN', name: 'Garmin Ltd.', sector: 'Consumer Discretionary' },
  { symbol: 'DRI', name: 'Darden Restaurants Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corp.', sector: 'Consumer Discretionary' },
  { symbol: 'BWA', name: 'BorgWarner Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'POOL', name: 'Pool Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'MGM', name: 'MGM Resorts International', sector: 'Consumer Discretionary' },
  { symbol: 'WYNN', name: 'Wynn Resorts Limited', sector: 'Consumer Discretionary' },
  { symbol: 'TSCO', name: 'Tractor Supply Company', sector: 'Consumer Discretionary' },
  { symbol: 'LKQ', name: 'LKQ Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'ETSY', name: 'Etsy Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'KMX', name: 'CarMax Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'BBY', name: 'Best Buy Co. Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NWL', name: 'Newell Brands Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'HAS', name: 'Hasbro Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'WHR', name: 'Whirlpool Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'PVH', name: 'PVH Corp.', sector: 'Consumer Discretionary' },
  { symbol: 'TPR', name: 'Tapestry Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'VFC', name: 'V.F. Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'GME', name: 'GameStop Corp.', sector: 'Consumer Discretionary' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'LCID', name: 'Lucid Group Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NIO', name: 'NIO Inc.', sector: 'Consumer Discretionary' },

  // ═══════════════════════════════════════════════════════════════════════════
  // COMMUNICATION SERVICES (25+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', sector: 'Communication' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', sector: 'Communication' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Communication' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication' },
  { symbol: 'DIS', name: 'Walt Disney Company', sector: 'Communication' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', sector: 'Communication' },
  { symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication' },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'Communication' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', sector: 'Communication' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.', sector: 'Communication' },
  { symbol: 'EA', name: 'Electronic Arts Inc.', sector: 'Communication' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication' },
  { symbol: 'PARA', name: 'Paramount Global', sector: 'Communication' },
  { symbol: 'OMC', name: 'Omnicom Group Inc.', sector: 'Communication' },
  { symbol: 'IPG', name: 'Interpublic Group', sector: 'Communication' },
  { symbol: 'LYV', name: 'Live Nation Entertainment', sector: 'Communication' },
  { symbol: 'MTCH', name: 'Match Group Inc.', sector: 'Communication' },
  { symbol: 'FOXA', name: 'Fox Corporation (Class A)', sector: 'Communication' },
  { symbol: 'FOX', name: 'Fox Corporation (Class B)', sector: 'Communication' },
  { symbol: 'NWS', name: 'News Corporation (Class B)', sector: 'Communication' },
  { symbol: 'NWSA', name: 'News Corporation (Class A)', sector: 'Communication' },
  { symbol: 'AMC', name: 'AMC Entertainment Holdings', sector: 'Communication' },

  // ═══════════════════════════════════════════════════════════════════════════
  // INDUSTRIALS (75+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'GE', name: 'General Electric Company', sector: 'Industrial' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrial' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrial' },
  { symbol: 'HON', name: 'Honeywell International', sector: 'Industrial' },
  { symbol: 'UNP', name: 'Union Pacific Corporation', sector: 'Industrial' },
  { symbol: 'BA', name: 'Boeing Company', sector: 'Industrial' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrial' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial' },
  { symbol: 'LMT', name: 'Lockheed Martin Corp.', sector: 'Industrial' },
  { symbol: 'ETN', name: 'Eaton Corporation plc', sector: 'Industrial' },
  { symbol: 'ADP', name: 'Automatic Data Processing', sector: 'Industrial' },
  { symbol: 'GD', name: 'General Dynamics Corp.', sector: 'Industrial' },
  { symbol: 'NOC', name: 'Northrop Grumman Corp.', sector: 'Industrial' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.', sector: 'Industrial' },
  { symbol: 'WM', name: 'Waste Management Inc.', sector: 'Industrial' },
  { symbol: 'CSX', name: 'CSX Corporation', sector: 'Industrial' },
  { symbol: 'NSC', name: 'Norfolk Southern Corp.', sector: 'Industrial' },
  { symbol: 'EMR', name: 'Emerson Electric Co.', sector: 'Industrial' },
  { symbol: 'FDX', name: 'FedEx Corporation', sector: 'Industrial' },
  { symbol: 'PH', name: 'Parker-Hannifin Corp.', sector: 'Industrial' },
  { symbol: 'JCI', name: 'Johnson Controls International', sector: 'Industrial' },
  { symbol: 'CTAS', name: 'Cintas Corporation', sector: 'Industrial' },
  { symbol: 'TT', name: 'Trane Technologies plc', sector: 'Industrial' },
  { symbol: 'MMM', name: '3M Company', sector: 'Industrial' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', sector: 'Industrial' },
  { symbol: 'CARR', name: 'Carrier Global Corp.', sector: 'Industrial' },
  { symbol: 'OTIS', name: 'Otis Worldwide Corporation', sector: 'Industrial' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.', sector: 'Industrial' },
  { symbol: 'AME', name: 'AMETEK Inc.', sector: 'Industrial' },
  { symbol: 'CMI', name: 'Cummins Inc.', sector: 'Industrial' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc.', sector: 'Industrial' },
  { symbol: 'LHX', name: 'L3Harris Technologies', sector: 'Industrial' },
  { symbol: 'FAST', name: 'Fastenal Company', sector: 'Industrial' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.', sector: 'Industrial' },
  { symbol: 'RSG', name: 'Republic Services Inc.', sector: 'Industrial' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line', sector: 'Industrial' },
  { symbol: 'CPRT', name: 'Copart Inc.', sector: 'Industrial' },
  { symbol: 'XYL', name: 'Xylem Inc.', sector: 'Industrial' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake', sector: 'Industrial' },
  { symbol: 'HWM', name: 'Howmet Aerospace Inc.', sector: 'Industrial' },
  { symbol: 'PWR', name: 'Quanta Services Inc.', sector: 'Industrial' },
  { symbol: 'DOV', name: 'Dover Corporation', sector: 'Industrial' },
  { symbol: 'IEX', name: 'IDEX Corporation', sector: 'Industrial' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc.', sector: 'Industrial' },
  { symbol: 'HUBB', name: 'Hubbell Incorporated', sector: 'Industrial' },
  { symbol: 'EFX', name: 'Equifax Inc.', sector: 'Industrial' },
  { symbol: 'FTV', name: 'Fortive Corporation', sector: 'Industrial' },
  { symbol: 'SNA', name: 'Snap-on Incorporated', sector: 'Industrial' },
  { symbol: 'EXPD', name: 'Expeditors International', sector: 'Industrial' },
  { symbol: 'SWK', name: 'Stanley Black & Decker', sector: 'Industrial' },
  { symbol: 'J', name: 'Jacobs Solutions Inc.', sector: 'Industrial' },
  { symbol: 'JBHT', name: 'J.B. Hunt Transport Services', sector: 'Industrial' },
  { symbol: 'MAS', name: 'Masco Corporation', sector: 'Industrial' },
  { symbol: 'NDSN', name: 'Nordson Corporation', sector: 'Industrial' },
  { symbol: 'PNR', name: 'Pentair plc', sector: 'Industrial' },
  { symbol: 'ALLE', name: 'Allegion plc', sector: 'Industrial' },
  { symbol: 'GPC', name: 'Genuine Parts Company', sector: 'Industrial' },
  { symbol: 'TDG', name: 'TransDigm Group Inc.', sector: 'Industrial' },
  { symbol: 'AXON', name: 'Axon Enterprise Inc.', sector: 'Industrial' },
  { symbol: 'GNRC', name: 'Generac Holdings Inc.', sector: 'Industrial' },
  { symbol: 'LDOS', name: 'Leidos Holdings Inc.', sector: 'Industrial' },
  { symbol: 'PAYC', name: 'Paycom Software Inc.', sector: 'Industrial' },
  { symbol: 'PAYX', name: 'Paychex Inc.', sector: 'Industrial' },
  { symbol: 'ROL', name: 'Rollins Inc.', sector: 'Industrial' },
  { symbol: 'UAL', name: 'United Airlines Holdings', sector: 'Industrial' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc.', sector: 'Industrial' },
  { symbol: 'AAL', name: 'American Airlines Group', sector: 'Industrial' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.', sector: 'Industrial' },
  { symbol: 'ALK', name: 'Alaska Air Group Inc.', sector: 'Industrial' },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONSUMER STAPLES (35+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Staples' },
  { symbol: 'PG', name: 'Procter & Gamble Co.', sector: 'Consumer Staples' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.', sector: 'Consumer Staples' },
  { symbol: 'KO', name: 'Coca-Cola Company', sector: 'Consumer Staples' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Staples' },
  { symbol: 'PM', name: 'Philip Morris International', sector: 'Consumer Staples' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', sector: 'Consumer Staples' },
  { symbol: 'MO', name: 'Altria Group Inc.', sector: 'Consumer Staples' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company', sector: 'Consumer Staples' },
  { symbol: 'EL', name: 'Estée Lauder Companies', sector: 'Consumer Staples' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corporation', sector: 'Consumer Staples' },
  { symbol: 'GIS', name: 'General Mills Inc.', sector: 'Consumer Staples' },
  { symbol: 'SYY', name: 'Sysco Corporation', sector: 'Consumer Staples' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland Co.', sector: 'Consumer Staples' },
  { symbol: 'KR', name: 'Kroger Co.', sector: 'Consumer Staples' },
  { symbol: 'STZ', name: 'Constellation Brands Inc.', sector: 'Consumer Staples' },
  { symbol: 'HSY', name: 'Hershey Company', sector: 'Consumer Staples' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.', sector: 'Consumer Staples' },
  { symbol: 'MNST', name: 'Monster Beverage Corp.', sector: 'Consumer Staples' },
  { symbol: 'KHC', name: 'Kraft Heinz Company', sector: 'Consumer Staples' },
  { symbol: 'K', name: 'Kellanova', sector: 'Consumer Staples' },
  { symbol: 'CAG', name: 'Conagra Brands Inc.', sector: 'Consumer Staples' },
  { symbol: 'SJM', name: 'J. M. Smucker Company', sector: 'Consumer Staples' },
  { symbol: 'TSN', name: 'Tyson Foods Inc.', sector: 'Consumer Staples' },
  { symbol: 'HRL', name: 'Hormel Foods Corporation', sector: 'Consumer Staples' },
  { symbol: 'MKC', name: 'McCormick & Company', sector: 'Consumer Staples' },
  { symbol: 'CLX', name: 'Clorox Company', sector: 'Consumer Staples' },
  { symbol: 'CHD', name: 'Church & Dwight Co. Inc.', sector: 'Consumer Staples' },
  { symbol: 'CPB', name: 'Campbell Soup Company', sector: 'Consumer Staples' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Co.', sector: 'Consumer Staples' },
  { symbol: 'BG', name: 'Bunge Limited', sector: 'Consumer Staples' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance', sector: 'Consumer Staples' },
  { symbol: 'DG', name: 'Dollar General Corp.', sector: 'Consumer Staples' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.', sector: 'Consumer Staples' },

  // ═══════════════════════════════════════════════════════════════════════════
  // ENERGY (25+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger Limited', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources Inc.', sector: 'Energy' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corp.', sector: 'Energy' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources', sector: 'Energy' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'VLO', name: 'Valero Energy Corporation', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'WMB', name: 'Williams Companies Inc.', sector: 'Energy' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.', sector: 'Energy' },
  { symbol: 'HAL', name: 'Halliburton Company', sector: 'Energy' },
  { symbol: 'DVN', name: 'Devon Energy Corporation', sector: 'Energy' },
  { symbol: 'HES', name: 'Hess Corporation', sector: 'Energy' },
  { symbol: 'BKR', name: 'Baker Hughes Company', sector: 'Energy' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.', sector: 'Energy' },
  { symbol: 'OKE', name: 'ONEOK Inc.', sector: 'Energy' },
  { symbol: 'TRGP', name: 'Targa Resources Corp.', sector: 'Energy' },
  { symbol: 'MRO', name: 'Marathon Oil Corporation', sector: 'Energy' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy' },
  { symbol: 'CTRA', name: 'Coterra Energy Inc.', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UTILITIES (30+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'NEE', name: 'NextEra Energy Inc.', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy Corporation', sector: 'Utilities' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
  { symbol: 'D', name: 'Dominion Energy Inc.', sector: 'Utilities' },
  { symbol: 'AEP', name: 'American Electric Power', sector: 'Utilities' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.', sector: 'Utilities' },
  { symbol: 'EXC', name: 'Exelon Corporation', sector: 'Utilities' },
  { symbol: 'PCG', name: 'PG&E Corporation', sector: 'Utilities' },
  { symbol: 'CEG', name: 'Constellation Energy Corp.', sector: 'Utilities' },
  { symbol: 'ED', name: 'Consolidated Edison Inc.', sector: 'Utilities' },
  { symbol: 'WEC', name: 'WEC Energy Group Inc.', sector: 'Utilities' },
  { symbol: 'ES', name: 'Eversource Energy', sector: 'Utilities' },
  { symbol: 'AWK', name: 'American Water Works Co.', sector: 'Utilities' },
  { symbol: 'EIX', name: 'Edison International', sector: 'Utilities' },
  { symbol: 'DTE', name: 'DTE Energy Company', sector: 'Utilities' },
  { symbol: 'AEE', name: 'Ameren Corporation', sector: 'Utilities' },
  { symbol: 'ETR', name: 'Entergy Corporation', sector: 'Utilities' },
  { symbol: 'PPL', name: 'PPL Corporation', sector: 'Utilities' },
  { symbol: 'FE', name: 'FirstEnergy Corp.', sector: 'Utilities' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc.', sector: 'Utilities' },
  { symbol: 'CMS', name: 'CMS Energy Corporation', sector: 'Utilities' },
  { symbol: 'ATO', name: 'Atmos Energy Corporation', sector: 'Utilities' },
  { symbol: 'NI', name: 'NiSource Inc.', sector: 'Utilities' },
  { symbol: 'LNT', name: 'Alliant Energy Corp.', sector: 'Utilities' },
  { symbol: 'EVRG', name: 'Evergy Inc.', sector: 'Utilities' },
  { symbol: 'NRG', name: 'NRG Energy Inc.', sector: 'Utilities' },
  { symbol: 'PNW', name: 'Pinnacle West Capital Corp.', sector: 'Utilities' },

  // ═══════════════════════════════════════════════════════════════════════════
  // REAL ESTATE (30+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate' },
  { symbol: 'AMT', name: 'American Tower Corporation', sector: 'Real Estate' },
  { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'Real Estate' },
  { symbol: 'CCI', name: 'Crown Castle Inc.', sector: 'Real Estate' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'WELL', name: 'Welltower Inc.', sector: 'Real Estate' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.', sector: 'Real Estate' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.', sector: 'Real Estate' },
  { symbol: 'O', name: 'Realty Income Corporation', sector: 'Real Estate' },
  { symbol: 'VICI', name: 'VICI Properties Inc.', sector: 'Real Estate' },
  { symbol: 'SBAC', name: 'SBA Communications Corp.', sector: 'Real Estate' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc.', sector: 'Real Estate' },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate' },
  { symbol: 'WY', name: 'Weyerhaeuser Company', sector: 'Real Estate' },
  { symbol: 'ARE', name: 'Alexandria Real Estate', sector: 'Real Estate' },
  { symbol: 'EXR', name: 'Extra Space Storage Inc.', sector: 'Real Estate' },
  { symbol: 'VTR', name: 'Ventas Inc.', sector: 'Real Estate' },
  { symbol: 'MAA', name: 'Mid-America Apartment', sector: 'Real Estate' },
  { symbol: 'UDR', name: 'UDR Inc.', sector: 'Real Estate' },
  { symbol: 'ESS', name: 'Essex Property Trust Inc.', sector: 'Real Estate' },
  { symbol: 'HST', name: 'Host Hotels & Resorts Inc.', sector: 'Real Estate' },
  { symbol: 'INVH', name: 'Invitation Homes Inc.', sector: 'Real Estate' },
  { symbol: 'IRM', name: 'Iron Mountain Incorporated', sector: 'Real Estate' },
  { symbol: 'REG', name: 'Regency Centers Corp.', sector: 'Real Estate' },
  { symbol: 'KIM', name: 'Kimco Realty Corporation', sector: 'Real Estate' },
  { symbol: 'CPT', name: 'Camden Property Trust', sector: 'Real Estate' },
  { symbol: 'BXP', name: 'Boston Properties Inc.', sector: 'Real Estate' },

  // ═══════════════════════════════════════════════════════════════════════════
  // MATERIALS (30+ stocks)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'LIN', name: 'Linde plc', sector: 'Materials' },
  { symbol: 'APD', name: 'Air Products and Chemicals', sector: 'Materials' },
  { symbol: 'SHW', name: 'Sherwin-Williams Company', sector: 'Materials' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.', sector: 'Materials' },
  { symbol: 'NEM', name: 'Newmont Corporation', sector: 'Materials' },
  { symbol: 'ECL', name: 'Ecolab Inc.', sector: 'Materials' },
  { symbol: 'CTVA', name: 'Corteva Inc.', sector: 'Materials' },
  { symbol: 'DOW', name: 'Dow Inc.', sector: 'Materials' },
  { symbol: 'DD', name: 'DuPont de Nemours Inc.', sector: 'Materials' },
  { symbol: 'NUE', name: 'Nucor Corporation', sector: 'Materials' },
  { symbol: 'VMC', name: 'Vulcan Materials Company', sector: 'Materials' },
  { symbol: 'MLM', name: 'Martin Marietta Materials', sector: 'Materials' },
  { symbol: 'PPG', name: 'PPG Industries Inc.', sector: 'Materials' },
  { symbol: 'IFF', name: 'International Flavors', sector: 'Materials' },
  { symbol: 'BALL', name: 'Ball Corporation', sector: 'Materials' },
  { symbol: 'AVY', name: 'Avery Dennison Corporation', sector: 'Materials' },
  { symbol: 'FMC', name: 'FMC Corporation', sector: 'Materials' },
  { symbol: 'CF', name: 'CF Industries Holdings', sector: 'Materials' },
  { symbol: 'MOS', name: 'Mosaic Company', sector: 'Materials' },
  { symbol: 'ALB', name: 'Albemarle Corporation', sector: 'Materials' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.', sector: 'Materials' },
  { symbol: 'PKG', name: 'Packaging Corp of America', sector: 'Materials' },
  { symbol: 'IP', name: 'International Paper Co.', sector: 'Materials' },
  { symbol: 'EMN', name: 'Eastman Chemical Company', sector: 'Materials' },
  { symbol: 'CE', name: 'Celanese Corporation', sector: 'Materials' },
  { symbol: 'WRK', name: 'WestRock Company', sector: 'Materials' },
  { symbol: 'SEE', name: 'Sealed Air Corporation', sector: 'Materials' },
  { symbol: 'AMCR', name: 'Amcor plc', sector: 'Materials' },

  // ═══════════════════════════════════════════════════════════════════════════
  // ETFs (Popular Trading ETFs)
  // ═══════════════════════════════════════════════════════════════════════════
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', sector: 'ETF' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', sector: 'ETF' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', sector: 'ETF' },
  { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average', sector: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', sector: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', sector: 'ETF' },
  { symbol: 'VXX', name: 'iPath Series B S&P 500 VIX', sector: 'ETF' },
  { symbol: 'UVXY', name: 'ProShares Ultra VIX Short-Term', sector: 'ETF' },
  { symbol: 'SQQQ', name: 'ProShares UltraPro Short QQQ', sector: 'ETF' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', sector: 'ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLV', name: 'Health Care Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLI', name: 'Industrial Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLY', name: 'Consumer Discretionary SPDR', sector: 'ETF' },
  { symbol: 'XLP', name: 'Consumer Staples Select SPDR', sector: 'ETF' },
  { symbol: 'XLU', name: 'Utilities Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLB', name: 'Materials Select Sector SPDR', sector: 'ETF' },
  { symbol: 'XLRE', name: 'Real Estate Select Sector SPDR', sector: 'ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', sector: 'ETF' },
  { symbol: 'SLV', name: 'iShares Silver Trust', sector: 'ETF' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond', sector: 'ETF' },
  { symbol: 'HYG', name: 'iShares iBoxx High Yield Corporate', sector: 'ETF' },
  { symbol: 'LQD', name: 'iShares iBoxx Investment Grade', sector: 'ETF' },
  { symbol: 'EEM', name: 'iShares MSCI Emerging Markets', sector: 'ETF' },
  { symbol: 'EFA', name: 'iShares MSCI EAFE ETF', sector: 'ETF' },
  { symbol: 'VWO', name: 'Vanguard FTSE Emerging Markets', sector: 'ETF' },
  { symbol: 'VEA', name: 'Vanguard FTSE Developed Markets', sector: 'ETF' },
  { symbol: 'IEMG', name: 'iShares Core MSCI Emerging', sector: 'ETF' },
  { symbol: 'AGG', name: 'iShares Core U.S. Aggregate Bond', sector: 'ETF' },
  { symbol: 'BND', name: 'Vanguard Total Bond Market ETF', sector: 'ETF' },
  { symbol: 'SPYG', name: 'SPDR S&P 500 Growth ETF', sector: 'ETF' },
  { symbol: 'SPYV', name: 'SPDR S&P 500 Value ETF', sector: 'ETF' },
  { symbol: 'IVV', name: 'iShares Core S&P 500 ETF', sector: 'ETF' },
  { symbol: 'VIG', name: 'Vanguard Dividend Appreciation', sector: 'ETF' },
  { symbol: 'VYM', name: 'Vanguard High Dividend Yield', sector: 'ETF' },
  { symbol: 'SCHD', name: 'Schwab U.S. Dividend Equity', sector: 'ETF' },
  { symbol: 'VNQ', name: 'Vanguard Real Estate ETF', sector: 'ETF' },
]

/**
 * Search stocks by symbol or name
 * Returns up to 10 matching results
 */
export function searchStocks(query: string): StockInfo[] {
  if (!query || query.length === 0) {
    return []
  }

  const q = query.toUpperCase().trim()

  // Sort by relevance:
  // 1. Exact symbol match
  // 2. Symbol starts with query
  // 3. Name contains query
  const results = POPULAR_STOCKS
    .filter(stock =>
      stock.symbol.includes(q) ||
      stock.name.toUpperCase().includes(q)
    )
    .sort((a, b) => {
      // Exact symbol match first
      if (a.symbol === q) return -1
      if (b.symbol === q) return 1

      // Symbol starts with query
      if (a.symbol.startsWith(q) && !b.symbol.startsWith(q)) return -1
      if (b.symbol.startsWith(q) && !a.symbol.startsWith(q)) return 1

      // Both start with query, sort alphabetically
      if (a.symbol.startsWith(q) && b.symbol.startsWith(q)) {
        return a.symbol.localeCompare(b.symbol)
      }

      // Name match, sort by symbol
      return a.symbol.localeCompare(b.symbol)
    })
    .slice(0, 10)

  return results
}

/**
 * Check if a symbol exists in our database
 */
export function isKnownSymbol(symbol: string): boolean {
  return POPULAR_STOCKS.some(stock => stock.symbol === symbol.toUpperCase())
}

/**
 * Get stock info by symbol
 */
export function getStockInfo(symbol: string): StockInfo | undefined {
  return POPULAR_STOCKS.find(stock => stock.symbol === symbol.toUpperCase())
}

/**
 * Get count of stocks in the database
 */
export function getStockCount(): number {
  return POPULAR_STOCKS.length
}
